config/routes.rb
require 'sidekiq/web'

def json_resources(name)
  resources name, only: [:index, :show, :create, :update, :destroy]
end

Atmosphere::Engine.routes.draw do
  root 'home#index'

  devise_for :users,
             class_name: 'Atmosphere::User',
             controllers: {
               omniauth_callbacks: 'atmosphere/users/omniauth_callbacks'
             },
             module: :devise

  get 'jobs/show'
  resource :profile, only: [:show, :update] do
    member do
      put :update_password
      put :reset_private_token
    end
  end

  constraint = ->(request) { request.env['warden'].authenticate? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
    get 'admin/jobs' => 'admin/jobs#show', as: :jobs
  end

  namespace :admin do
    resources :appliance_sets, only: [:index, :show, :edit, :update, :destroy]
    resources :appliance_types do
      member do
        put :assign_virtual_machine_template
      end
      resources :port_mapping_templates, except: [:show] do
        resources :endpoints, except: [:show]
      end
      resources :appliance_configuration_templates, except: [:show]
    end
    resources :tenants
    resources :virtual_machines, only: [:index, :show] do
      member do
        post :save_as_template
        post :reboot
      end
    end
    resources :virtual_machine_templates, except: [:new, :create] do
      member do
        get :select_destination
        post :migrate
      end
    end
    resources :virtual_machine_flavors, only: [:edit, :update]
    resources :user_keys, except: [:edit, :update]
    resources :funds
    resources :tenant_funds, only: [:create, :destroy]
    resources :user_funds, only: [:create, :destroy, :update]
    resources :billing_logs, only: [:index]
    resources :migration_jobs, only: [:index]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :compute_sites, only: [:index, :show]

      resources :virtual_machine_flavors, only: [:index]

      json_resources :appliance_types

      get 'appliance_types/:id/endpoints/:service_name/:invocation_path' =>
          'appliance_types#endpoint_payload',
          as: 'appliance_types_endpoint_payload',
          constraints: { invocation_path: /[\w\.-]+(\/{0,1}[\w\.-]+)+/ },
          defaults: { format: :text }

      json_resources :port_mapping_templates
      resources :endpoints do
        member do
          get :descriptor
        end
      end
      json_resources :port_mapping_properties
      json_resources :appliance_configuration_templates
      resources :appliance_configuration_instances, only: [:index, :show]
      resources :http_mappings, only: [:index, :show, :update]
      resources :port_mappings, only: [:index, :show]
      resources :actions, only: [:index, :show]
      json_resources :appliance_sets

      resources :appliances do
        member do
          get :endpoints
          post :action
        end
      end

      resources :dev_mode_property_sets, only: [:index, :show, :update]
      resources :virtual_machines, only: [:index, :show]
      resources :virtual_machine_templates, only: [:index]
      json_resources :users
      resources :user_keys, only: [:index, :show, :create, :destroy]

      get 'clew/appliance_instances' => 'clew#appliance_instances'
      get 'clew/appliance_types' => 'clew#appliance_types'
    end
  end

  get 'help' => 'help#index'
  get 'help/api' => 'help#api'
  get 'help/api/:category' => 'help#api', as: 'help_api_file'
end

app/models/atmosphere/compute_site.rb
# == Schema Information
#
# Table name: compute_sites
#
#  id                :integer          not null, primary key
#  site_id           :string(255)      not null
#  name              :string(255)
#  location          :string(255)
#  site_type         :string(255)      default("private")
#  technology        :string(255)
#  http_proxy_url    :string(255)
#  https_proxy_url   :string(255)
#  config            :text
#  template_filters  :text
#  created_at        :datetime
#  updated_at        :datetime
#  wrangler_url      :string(255)
#  wrangler_username :string(255)
#  wrangler_password :string(255)
#  active            :boolean          default(TRUE)
#
module Atmosphere
  class ComputeSite < ActiveRecord::Base
    extend Enumerize

    has_many :virtual_machines,
      dependent: :destroy,
      class_name: 'Atmosphere::VirtualMachine'

    has_many :virtual_machine_templates,
      dependent: :destroy,
      class_name: 'Atmosphere::VirtualMachineTemplate'

    has_many :port_mapping_properties,
      dependent: :destroy,
      class_name: 'Atmosphere::PortMappingProperty'

    has_many :virtual_machine_flavors,
      dependent: :destroy,
      class_name: 'Atmosphere::VirtualMachineFlavor'

    # Required for API (returning all compute sites on which a given AT can be deployed)
    has_many :appliance_types,
      through: :virtual_machine_templates,
      class_name: 'Atmosphere::ApplianceType'

    has_many :funds,
      through: :compute_site_funds,
      class_name: 'Atmosphere::Fund'

    has_many :compute_site_funds,
      dependent: :destroy,
      class_name: 'Atmosphere::ComputeSiteFund'

    has_many :appliances,
      through: :appliance_compute_sites,
      class_name: 'Atmosphere::Appliance'

    has_many :appliance_compute_sites,
      dependent: :destroy,
      class_name: 'Atmosphere::ApplianceComputeSite'

    has_many :migration_job_cs_source,
      dependent: :destroy,
      class_name: 'Atmosphere::MigrationJob',
      foreign_key: 'compute_site_source_id'

    has_many :migration_job_cs_desination,
      dependent: :destroy,
      class_name: 'Atmosphere::MigrationJob',
      foreign_key: 'compute_site_destination_id'

    validates :site_id, presence: true

    validates :site_type,
              presence: true,
              inclusion: %w(public private)

    validates :technology,
              presence: true,
              inclusion: %w(openstack aws azure rackspace google_compute)

    validate :nic_provider_class_defined, if: :nic_provider_class_name?

    enumerize :site_type, in: [:public, :private], predicates: true
    enumerize :technology,
              in: [:openstack, :aws, :azure, :rackspace, :google_compute],
              predicates: true

    scope :with_appliance_type, ->(appliance_type) do
      joins(virtual_machines: {appliances: :appliance_set})
        .where(
          atmosphere_appliances: {
            appliance_type_id: appliance_type
          },
          atmosphere_appliance_sets: {
            appliance_set_type: [:workflow, :portal]
          }
        ).readonly(false)
    end

    scope :with_deployment, ->(deployment) do
      joins(virtual_machines: :deployments)
        .where(
          deployments: {
            id: deployment.id
          }
        ).readonly(false)
    end

    scope :with_dev_property_set, ->(dev_mode_property_set) do
      joins(virtual_machines: { appliances: :dev_mode_property_set })
        .where(
          atmosphere_dev_mode_property_sets: {
            id: dev_mode_property_set.id
          }
        ).readonly(false)
    end

    scope :with_appliance, ->(appliance) do
      joins(virtual_machines: :appliances)
        .where(atmosphere_appliances: {id: appliance.id})
    end

    scope :active, -> { where(active: true) }

    scope :funded_by, ->(fund) do
      joins(:funds)
        .where(atmosphere_funds: { id: fund.id })
    end

    after_update :update_cloud_client, if: :config_changed?
    after_destroy :unregister_cloud_client

    def to_s
      name
    end

    def cloud_client
      Atmosphere.get_cloud_client(self.site_id) || register_cloud_client
    end

    def dnat_client
      DnatWrangler.new(wrangler_url, wrangler_username, wrangler_password)
    end

    def proxy_urls_changed?
      previously_changed?('http_proxy_url', 'https_proxy_url')
    end

    def site_id_previously_changed?
      previously_changed?('site_id')
    end

    def default_flavor
      virtual_machine_flavors.first
    end

    def nic_provider_class_defined
      klass = Module.const_get(nic_provider_class_name)
      unless klass.is_a?(Class)
        errors.add(
          :nic_provider_class_name,
          "#{nic_provider_class_name} is not a class"
        )
      end
      rescue NameError
        errors.add(
          :nic_provider_class_name,
          "#{nic_provider_class_name} class is undefined"
        )
    end

    private

    def update_cloud_client
      unless config.blank?
        register_cloud_client
      else
        unregister_cloud_client
      end
    end

    def register_cloud_client
      cloud_site_conf = JSON.parse(self.config).symbolize_keys
      client = Fog::Compute.new(cloud_site_conf)
      Atmosphere.register_cloud_client(self.site_id, client)
      client
    end

    def unregister_cloud_client
      Atmosphere.unregister_cloud_client(site_id)
    end

    def previously_changed?(*args)
      !(previous_changes.keys & args).empty?
    end
  end
end

app/controllers/atmosphere/api/v1/compute_sites_controller.rb
module Atmosphere
  module Api
    module V1
      class ComputeSitesController < Atmosphere::Api::ApplicationController
        load_and_authorize_resource :tenant,
                                    parent: false,
                                    class: 'Atmosphere::Tenant'

        respond_to :json

        def index
          respond_with @tenants.where(filter).order(:id),
                       root: :compute_sites
        end

        def show
          respond_with @tenant,
                       root: :compute_site
        end

        def model_class
          Atmosphere::Tenant
        end

        private

        def filter
          super.tap do |f|
            f[:tenant_type] = params[:site_type] if params[:site_type]
            f[:tenant_id] = params[:site_id] if params[:site_id]
          end
        end
      end
    end
  end
end

app/views/atmosphere/admin/compute_sites/_form.html.haml
= simple_form_for([:admin, @compute_site]) do |f|
  = f.error_notification

  .inputs
    = f.input :site_id
    = f.input :name
    = f.input :active
    = f.input :location
    = f.input :site_type
    = f.input :technology
    = f.input :http_proxy_url
    = f.input :https_proxy_url
    = f.input :config, as: :text
    = f.input :template_filters, as: :text
    = f.input :wrangler_url
    = f.input :wrangler_username
    = f.input :wrangler_password, as: :string

  .actions
    = f.button :submit, class: 'btn btn-success'

app/views/atmosphere/admin/compute_sites/index.html.haml
%h1
  = t('compute_sites.long_title_single')
  .pull-right
    = link_to new_admin_compute_site_path,
      class: 'btn btn-success', title: t('compute_sites.new') do
      = icon 'plus'
      = t('add_new')

%p
  %table.table.table-hover.table-condensed
    %tr
      %th= t('compute_sites.site')
      %th= t('compute_sites.name')
      %th= t('compute_sites.location')
      %th= t('compute_sites.site_type')
      %th= t('compute_sites.technology')
      %th.actions
        = t('actions')

    - @compute_sites.each do |compute_site|
      %tr
        %td.monospace
          = compute_site.site_id
        %td= compute_site.name
        %td= compute_site.location
        %td= compute_site.site_type
        %td= compute_site.technology
        %td.actions
          .btn-group
            = link_to admin_compute_site_path(compute_site),
              class: 'btn btn-success btn-xs', title: t('compute_sites.show') do
              =icon 'bars'
            = link_to edit_admin_compute_site_path(compute_site),
              class: 'btn btn-warning btn-xs', title: t('compute_sites.edit') do
              =icon 'edit'
            = link_to admin_compute_site_path(compute_site), method: :delete, data: { confirm: t('are_you_sure_cs') },
              class: 'btn btn-danger btn-xs', title: t('compute_sites.remove') do
              =icon 'trash-o'


%h2
  = t('flavor_os_family.long_title')

%p
  %table.table.table-hover.table-condensed
    %tr
      %th= t('compute_sites.site')
      %th= t('virtual_machine_flavor.flavor_name')
      %th
        .pull-right= t('virtual_machine_flavor.cpu')
      %th
        .pull-right= t('virtual_machine_flavor.memory')
      %th
        .pull-right= t('virtual_machine_flavor.hdd')
      %th
        .pull-right= t('virtual_machine_flavor.supported_architectures')

      = each_os_family do |os_family|
        %th
          .pull-right
            = os_family.name
            = t('flavor_os_family.hourly_cost')

      %th.col-md-2
        .pull-right= t 'actions'


    - @compute_sites.each do |compute_site|
      - compute_site.virtual_machine_flavors.each do |flavor|
        %tr
          %td.monospace= compute_site.site_id
          %td
            - if flavor.active
              = flavor.flavor_name
            - else
              %i.text-muted
                = flavor.flavor_name
                = surround '(',')' do
                  inactive
          %td
            .pull-right= flavor.cpu
          %td
            .pull-right= flavor.memory
          %td
            .pull-right= flavor.hdd
          %td
            .pull-right= flavor.supported_architectures

          = each_os_family do |os_family|
            %td
              .pull-right
                = flavor.get_hourly_cost_for(os_family)

          %td
            .btn-group.pull-right
              = link_to edit_admin_virtual_machine_flavor_path(flavor),
                class: 'btn btn-warning btn-xs has_bottom_tooltip',
                title: t('flavor_os_family.update.help') do
                = icon 'edit'