config/routes.rb
require 'sidekiq/web'

def json_resources(name)
  resources name, only: [:index, :show, :create, :update, :destroy]
end

Atmosphere::Engine.routes.draw do
  root 'home#index'

  devise_for :users,
             class_name: 'Atmosphere::User',
             controllers: {
               omniauth_callbacks: 'atmosphere/users/omniauth_callbacks'
             },
             module: :devise

  get 'jobs/show'
  resource :profile, only: [:show, :update] do
    member do
      put :update_password
      put :reset_private_token
    end
  end

  constraint = ->(request) { request.env['warden'].authenticate? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
    get 'admin/jobs' => 'admin/jobs#show', as: :jobs
  end

  namespace :admin do
    resources :appliance_sets, only: [:index, :show, :edit, :update, :destroy]
    resources :appliance_types do
      member do
        put :assign_virtual_machine_template
      end
      resources :port_mapping_templates, except: [:show] do
        resources :endpoints, except: [:show]
      end
      resources :appliance_configuration_templates, except: [:show]
    end
    resources :tenants
    resources :virtual_machines, only: [:index, :show] do
      member do
        post :save_as_template
        post :reboot
      end
    end
    resources :virtual_machine_templates, except: [:new, :create] do
      member do
        get :select_destination
        post :migrate
      end
    end
    resources :virtual_machine_flavors, only: [:edit, :update]
    resources :user_keys, except: [:edit, :update]
    resources :funds
    resources :tenant_funds, only: [:create, :destroy]
    resources :user_funds, only: [:create, :destroy, :update]
    resources :billing_logs, only: [:index]
    resources :migration_jobs, only: [:index]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :compute_sites, only: [:index, :show]

      resources :virtual_machine_flavors, only: [:index]

      json_resources :appliance_types

      get 'appliance_types/:id/endpoints/:service_name/:invocation_path' =>
          'appliance_types#endpoint_payload',
          as: 'appliance_types_endpoint_payload',
          constraints: { invocation_path: /[\w\.-]+(\/{0,1}[\w\.-]+)+/ },
          defaults: { format: :text }

      json_resources :port_mapping_templates
      resources :endpoints do
        member do
          get :descriptor
        end
      end
      json_resources :port_mapping_properties
      json_resources :appliance_configuration_templates
      resources :appliance_configuration_instances, only: [:index, :show]
      resources :http_mappings, only: [:index, :show, :update]
      resources :port_mappings, only: [:index, :show]
      resources :actions, only: [:index, :show]
      json_resources :appliance_sets

      resources :appliances do
        member do
          get :endpoints
          post :action
        end
      end

      resources :dev_mode_property_sets, only: [:index, :show, :update]
      resources :virtual_machines, only: [:index, :show]
      resources :virtual_machine_templates, only: [:index]
      json_resources :users
      resources :user_keys, only: [:index, :show, :create, :destroy]

      get 'clew/appliance_instances' => 'clew#appliance_instances'
      get 'clew/appliance_types' => 'clew#appliance_types'
    end
  end

  get 'help' => 'help#index'
  get 'help/api' => 'help#api'
  get 'help/api/:category' => 'help#api', as: 'help_api_file'
end

app/models/appliance_set.rb
# == Schema Information
#
# Table name: appliance_sets
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  priority           :integer          default(50), not null
#  appliance_set_type :string(255)      default("workflow"), not null
#  user_id            :integer          not null
#  created_at         :datetime
#  updated_at         :datetime
#

class ApplianceSet < ActiveRecord::Base
  extend Enumerize

  belongs_to :user

  validates_presence_of :priority, :appliance_set_type, :user

  validates :priority, numericality: { only_integer: true }, inclusion: 1..100

  enumerize :appliance_set_type, in: [:portal, :development, :workflow]
  validates :appliance_set_type, inclusion: %w(portal development workflow)
  validates :appliance_set_type, uniqueness: { scope: :user }, if: 'appliance_set_type == "development" or appliance_set_type == "portal"'

  attr_readonly :appliance_set_type

  has_many :appliances, dependent: :destroy

  scope :with_vm, ->(virtual_machine) { joins(appliances: :virtual_machines).where(virtual_machines: {id: virtual_machine.id}) }

  scope :clew_appliances, -> (appliance_set_type) { where(:appliance_sets => { :appliance_set_type => appliance_set_type }).
      includes(:appliances).references(:appliances).
      includes(:appliances => :deployments).references(:appliances => :deployments).
      includes(:appliances => :appliance_type).references(:appliances => :appliance_type).
      includes(:appliances => :http_mappings).references(:appliances => :http_mappings).
      includes(:appliances => { :appliance_type => :port_mapping_templates } ).references(:appliances => { :appliance_type => :port_mapping_templates } ).
      includes(:appliances => { :http_mappings => :port_mapping_template } ).references(:appliances => { :http_mappings => :port_mapping_template } ).
      includes(:appliances => { :deployments => :virtual_machine }).references(:appliances => { :deployments => :virtual_machine }).
      includes(:appliances => { :appliance_type => { :port_mapping_templates => :endpoints } } ).references(:appliances => { :appliance_type => { :port_mapping_templates => :endpoints } }).
      includes(:appliances => { :deployments => { :virtual_machine => :port_mappings } } ).references(:appliances => { :deployments => { :virtual_machine => :port_mappings } }).
      includes(:appliances => { :deployments => { :virtual_machine => :compute_site } } ).references(:appliances => { :deployments => { :virtual_machine => :compute_site } }).
      includes(:appliances => { :deployments => { :virtual_machine => :virtual_machine_flavor } }).references(:appliances => { :deployments => { :virtual_machine => :virtual_machine_flavor } })}

  def production?
    not appliance_set_type.development?
  end

end

app/models/atmosphere/appliance_set.rb
# == Schema Information
#
# Table name: appliance_sets
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  priority           :integer          default(50), not null
#  appliance_set_type :string(255)      default("workflow"), not null
#  user_id            :integer          not null
#  created_at         :datetime
#  updated_at         :datetime
#
module Atmosphere
  class ApplianceSet < ActiveRecord::Base
    include Atmosphere::ApplianceSetExt
    extend Enumerize

    belongs_to :user,
               class_name: 'Atmosphere::User'

    has_many :appliances,
             class_name: 'Atmosphere::Appliance'

    validates :user, presence: true

    validates :priority,
              presence: true,
              numericality: { only_integer: true },
              inclusion: 1..100

    validates :appliance_set_type,
              presence: true,
              inclusion: %w(portal development workflow)

    validates :optimization_policy,
              inclusion: %w(manual),
              if: :optimization_policy

    validates :appliance_set_type,
              uniqueness: { scope: :user_id },
              if: 'appliance_set_type == "development" or appliance_set_type == "portal"'

    enumerize :appliance_set_type, in: [:portal, :development, :workflow]

    attr_readonly :appliance_set_type

    scope :with_vm, ->(virtual_machine) do
      joins(appliances: :virtual_machines).
        where(atmosphere_virtual_machines: { id: virtual_machine.id })
    end

    scope :clew_appliances, -> (appliance_set_type) do
      deps = if appliance_set_type.to_s == 'development'
               devel_clew_includes
             else
               prod_clew_includes
             end

      where(atmosphere_appliance_sets: {
              appliance_set_type: appliance_set_type
            }).includes(deps).references(deps)
    end

    def production?
      !appliance_set_type.development?
    end

    def development?
      appliance_set_type.development?
    end

    def self.devel_clew_includes
      basic_clew_includes.tap do |hsh|
        hsh[:appliances][:dev_mode_property_set] =
          { port_mapping_templates: :endpoints }
      end
    end

    def self.prod_clew_includes
      basic_clew_includes.tap do |hsh|
        hsh[:appliances][:appliance_type] =
          { port_mapping_templates: :endpoints }
      end
    end

    def self.basic_clew_includes
      {
        appliances: {
          deployments: {
            virtual_machine: [
              :port_mappings, :tenant, :virtual_machine_flavor
            ]
          },
          http_mappings: :port_mapping_template
        }
      }
    end
  end
end

app/controllers/api/v1/appliance_sets_controller.rb
module Api
  module V1
    class ApplianceSetsController < Api::ApplicationController
      before_filter :create_appliance_set, only: :create
      load_and_authorize_resource :appliance_set
      respond_to :json

      def index
        respond_with @appliance_sets.where(filter).order(:id)
      end

      def show
        respond_with @appliance_set
      end

      def create
        log_user_action "create new appliance set with following params #{params}"
        if conflicted? @appliance_set.appliance_set_type
          msg = "Unable to create two #{@appliance_set.appliance_set_type} appliance sets"
          render_json_error(msg, status: :conflict)
          log_user_action msg
        else
          @appliance_set.save!
          create_appliances if @appliances_params
          render json: @appliance_set, serializer: ApplianceSetSerializer, status: :created
          log_user_action "appliance set created: #{@appliance_set.to_json}"
        end
      end

      def update
        log_user_action "update appliance set #{@appliance_set.id} with following params #{params}"
        @appliance_set.update_attributes!(appliance_set_update_params)
        render json: @appliance_set, serializer: ApplianceSetSerializer
        log_user_action "appliance set updated: #{@appliance_set.to_json}"
      end

      def destroy
        log_user_action "destroy appliance set #{@appliance_set.id}"
        if @appliance_set.destroy
          render json: {}
          log_user_action "appliance set #{@appliance_set.id} destroyed"
        else
          render_error @appliance_set
        end
      end

      private
      def appliance_set_params
        @appliances_params = params[:appliance_set][:appliances] if params[:appliance_set][:appliances]
        params.require(:appliance_set).permit(:appliance_set_type, :name, :priority, :optimization_policy)
      end

      def appliance_set_update_params
        params.require(:appliance_set).permit(:name, :priority)
      end

      def create_appliance_set
        @appliance_set = ApplianceSet.new params[:appliance_set]
        @appliance_set.user = current_user
      end

      def create_appliances
        @appliances_params.each do |appl_params|
          appl_params[:appliance_set_id] = @appliance_set.id
          creator = ApplianceCreator.new(appl_params, mi_ticket)
          appl = creator.create!
          @appliance_set.appliances << appl
        end
      end

      def conflicted?(type)
        not type.workflow? and current_user.appliance_sets.where(appliance_set_type: type).count > 0
      end

      def set_appliance_sets
        if current_user
          @appliance_sets = load_all? ? ApplianceSet.all : current_user.appliance_sets
        end
      end
    end
  end
end

app/controllers/atmosphere/admin/appliance_sets_controller.rb
class Atmosphere::Admin::ApplianceSetsController < Atmosphere::Admin::ApplicationController
  load_and_authorize_resource :appliance_set,
    class: 'Atmosphere::ApplianceSet'

  # GET /admin/appliance_sets
  def index
    @appliance_sets = @appliance_sets.joins(:user).order('atmosphere_users.login', priority: :desc).group_by(&:user)
  end

  # GET /admin/appliance_sets/1
  def show
  end

  # GET /admin/appliance_sets/1/edit
  def edit
  end

  # PATCH/PUT /admin/appliance_sets/1
  def update
    if @appliance_set.update(appliance_set_params)
      redirect_to [:admin, @appliance_set], notice: 'ApplianceSet was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/appliance_sets/1
  def destroy
    Atmosphere::DestroyApplianceSet.new(@appliance_set).execute
    redirect_to admin_appliance_sets_url, notice: 'ApplianceSet was successfully destroyed.'
  end

  private

    # Only allow a trusted parameter "white list" through.
    def appliance_set_params
      params[:appliance_set].permit(:name, :priority)
    end
end

app/controllers/atmosphere/api/v1/appliance_sets_controller.rb
module Atmosphere
  module Api
    module V1
      class ApplianceSetsController < Atmosphere::Api::ApplicationController
        load_and_authorize_resource :appliance_set,
                                    class: 'Atmosphere::ApplianceSet'

        include Atmosphere::Api::Auditable

        respond_to :json

        before_action :create_appliance_set, only: :create

        def index
          respond_with @appliance_sets.where(filter).order(:id)
        end

        def show
          respond_with @appliance_set
        end

        def create
          if !@appliance_set.appliance_set_type
            render_json_error(
              I18n.t(
                'appliance_sets.invalid_type',
                type: appliance_set_params[:appliance_set_type]
              ),
              status: :unprocessable_entity,
              type: :record_invalid
            )
          elsif conflicted? @appliance_set.appliance_set_type
            msg = I18n.t(
              'appliance_sets.conflicted',
              type: @appliance_set.appliance_set_type
            )
            render_json_error(msg, status: :conflict)
            log_user_action msg
          else
            @appliance_set.save!
            create_appliances if @appliances_params
            render json: @appliance_set,
                   serializer: ApplianceSetSerializer,
                   status: :created
          end
        end

        def update
          @appliance_set.update_attributes!(appliance_set_update_params)
          render json: @appliance_set,
                 serializer: ApplianceSetSerializer
        end

        def destroy
          if Atmosphere::DestroyApplianceSet.new(@appliance_set).execute
            render json: {}
          else
            render_error @appliance_set
          end
        end

        private

        def appliance_set_params
          if params[:appliance_set] && params[:appliance_set][:appliances]
            @appliances_params = params[:appliance_set][:appliances]
          end

          allowed_params = [
            :appliance_set_type,
            :name,
            :priority,
            :optimization_policy
          ] + create_params_ext

          params.require(:appliance_set).
            permit(allowed_params)
        end

        def appliance_set_update_params
          params.require(:appliance_set).permit(:name, :priority)
        end

        def create_appliance_set
          @appliance_set = ApplianceSet.new(appliance_set_params)
          @appliance_set.user = current_user
        end

        def create_appliances
          @appliances_params.each do |appl_params|
            appl_params[:appliance_set_id] = @appliance_set.id
            creator = ApplianceCreator.new(appl_params, delegate_auth)
            appl = creator.build
            Atmosphere::CreateApplianceService.new(appl).execute
            @appliance_set.appliances << appl
          end
        end

        def conflicted?(type)
          !type.workflow? && as_with_type(type).count > 0
        end

        def as_with_type(type)
          current_user.appliance_sets.where(appliance_set_type: type)
        end

        def set_appliance_sets
          return unless current_user
          @appliance_sets = if load_all?
                              ApplianceSet.all
                            else
                              current_user.appliance_sets
                            end
        end

        def model_class
          Atmosphere::ApplianceSet
        end

        include Atmosphere::Api::V1::ApplianceSetsControllerExt
      end
    end
  end
end

app/views/atmosphere/admin/appliance_sets/_appliance_details.html.haml
= t('appliance_sets.fund')
%strong
  = succeed '.' do
    = appliance.fund ? appliance.fund.name : t('appliance_sets.no_fund_assigned')
= t('appliance_sets.amount_billed')
%strong
  = fund_balance_full_precision appliance.amount_billed
  = appliance.fund ? appliance.fund.currency_label : '?'
%br
- appliance.virtual_machines.each do |virtual_machine|
  = virtual_machine.appliance_type.name
  %br

app/views/atmosphere/admin/appliance_sets/_form.html.haml
= simple_form_for [:admin, @appliance_set] do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :priority
    = f.input :appliance_set_type, disabled: true
    = f.input :user, disabled: true

  %p
    .actions
      = f.submit t('save'), class: 'btn btn-success'

app/views/atmosphere/admin/appliance_sets/edit.html.haml
%h1
  = t('editing')
  = t('appliance_sets.long_title_single')

= render 'form'

%p
  .btn-group
    = link_to [:admin, @appliance_set],
      class: 'btn btn-success', title: t('appliance_sets.show') do
      =icon 'bars'
      = t('show')
    = link_to admin_appliance_sets_path,
      class: 'btn btn-default', title: t('back') do
      =icon 'reply'
      = t('back')

app/views/atmosphere/admin/appliance_sets/index.html.haml
%h1
  = t('appliance_sets.long_title')

%p
  %table.table.table-hover.table-condensed
    %tr
      %th= t('appliance_sets.user')
      %th= t('appliance_sets.type')
      %th= t('appliance_sets.appliance_type')
      %th= t('appliance_sets.virtual_machines')
      %th= t('appliance_sets.tenant')
      %th= t('appliance_sets.flavor')
      %th.actions= t('actions')

    - @appliance_sets.each do |user, sets|
      - sets.each_with_index do |appliance_set, i|
        %tr
          - if i==0
            %td{rowspan: sets.count}= user.login
          %td= appliance_set.appliance_set_type

          - if appliance_set.appliances.present?
            %td
              - appliance_set.appliances.each do |appliance|
                = render partial: 'appliance_details', locals: { appliance: appliance }
            %td
              - appliance_set.appliances.each do |appliance|
                = t('appliance_sets.billing_state')
                - label_map = {initial: :primary, prepaid: :success, expired: :danger, error: :danger}
                %span(class="label label-#{label_map[appliance.billing_state.to_sym]}")
                  = appliance.billing_state
                &nbsp;
                = t('appliance_sets.state')
                - label_map = {new: :primary, satisfied: :success, unsatisfied: :danger}
                %span(class="label label-#{label_map[appliance.state.to_sym]}")
                  = appliance.state
                %br
                - appliance.virtual_machines.each do |virtual_machine|
                  = virtual_machine.id_at_site
                  %br
            %td
              - appliance_set.appliances.each do |appliance|
                %br
                - appliance.virtual_machines.each do |virtual_machine|
                  = virtual_machine.tenant.name
                  %br
            %td
              - appliance_set.appliances.each do |appliance|
                %br
                - appliance.virtual_machines.each do |virtual_machine|
                  = virtual_machine.virtual_machine_flavor ? virtual_machine.virtual_machine_flavor.id_at_site : t('appliance_sets.no_flavor')
                  %br
          - else
            %td(colspan='4')
              = t('appliance_sets.no_appliances')

          %td.actions
            .btn-group
              = link_to [:admin, appliance_set],
                class: 'btn btn-success btn-xs', title: t('appliance_sets.show') do
                =icon 'bars'
              = link_to edit_admin_appliance_set_path(appliance_set),
                class: 'btn btn-warning btn-xs', title: t('appliance_sets.edit') do
                =icon 'edit'
              = link_to [:admin, appliance_set], method: :delete, data: { confirm: t('are_you_sure') },
                class: 'btn btn-danger btn-xs', title: t('appliance_sets.remove') do
                =icon 'trash-o'

app/views/atmosphere/admin/appliance_sets/show.html.haml
%h1
  = t('show')
  = t('appliance_sets.long_title_single')

%p
  %table.show-table
    %tr
      %td= t('appliance_set.name')
      %td= @appliance_set.name
    %tr
      %td= t('appliance_set.priority')
      %td= @appliance_set.priority
    %tr
      %td= t('appliance_set.appliance_set_type')
      %td= @appliance_set.appliance_set_type
    %tr
      %td= t('appliance_set.user')
      %td= @appliance_set.user

%p
  .btn-group
    = link_to edit_admin_appliance_set_path(@appliance_set),
      class: 'btn btn-warning', title: t('appliance_sets.edit') do
      =icon 'edit'
      = t('edit')
    = link_to admin_appliance_sets_path,
      class: 'btn btn-default', title: t('back') do
      =icon 'reply'
      = t('back')