config/routes.rb
require 'sidekiq/web'

def json_resources(name)
  resources name, only: [:index, :show, :create, :update, :destroy]
end

Atmosphere::Engine.routes.draw do
  root 'home#index'

  devise_for :users,
             class_name: 'Atmosphere::User',
             controllers: {
               omniauth_callbacks: 'atmosphere/users/omniauth_callbacks'
             },
             module: :devise

  get 'jobs/show'
  resource :profile, only: [:show, :update] do
    member do
      put :update_password
      put :reset_private_token
    end
  end

  constraint = ->(request) { request.env['warden'].authenticate? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
    get 'admin/jobs' => 'admin/jobs#show', as: :jobs
  end

  namespace :admin do
    resources :appliance_sets, only: [:index, :show, :edit, :update, :destroy]
    resources :appliance_types do
      member do
        put :assign_virtual_machine_template
      end
      resources :port_mapping_templates, except: [:show] do
        resources :endpoints, except: [:show]
      end
      resources :appliance_configuration_templates, except: [:show]
    end
    resources :tenants
    resources :virtual_machines, only: [:index, :show] do
      member do
        post :save_as_template
        post :reboot
      end
    end
    resources :virtual_machine_templates, except: [:new, :create] do
      member do
        get :select_destination
        post :migrate
      end
    end
    resources :virtual_machine_flavors, only: [:edit, :update]
    resources :user_keys, except: [:edit, :update]
    resources :funds
    resources :tenant_funds, only: [:create, :destroy]
    resources :user_funds, only: [:create, :destroy, :update]
    resources :billing_logs, only: [:index]
    resources :migration_jobs, only: [:index]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :compute_sites, only: [:index, :show]

      resources :virtual_machine_flavors, only: [:index]

      json_resources :appliance_types

      get 'appliance_types/:id/endpoints/:service_name/:invocation_path' =>
          'appliance_types#endpoint_payload',
          as: 'appliance_types_endpoint_payload',
          constraints: { invocation_path: /[\w\.-]+(\/{0,1}[\w\.-]+)+/ },
          defaults: { format: :text }

      json_resources :port_mapping_templates
      resources :endpoints do
        member do
          get :descriptor
        end
      end
      json_resources :port_mapping_properties
      json_resources :appliance_configuration_templates
      resources :appliance_configuration_instances, only: [:index, :show]
      resources :http_mappings, only: [:index, :show, :update]
      resources :port_mappings, only: [:index, :show]
      resources :actions, only: [:index, :show]
      json_resources :appliance_sets

      resources :appliances do
        member do
          get :endpoints
          post :action
        end
      end

      resources :dev_mode_property_sets, only: [:index, :show, :update]
      resources :virtual_machines, only: [:index, :show]
      resources :virtual_machine_templates, only: [:index]
      json_resources :users
      resources :user_keys, only: [:index, :show, :create, :destroy]

      get 'clew/appliance_instances' => 'clew#appliance_instances'
      get 'clew/appliance_types' => 'clew#appliance_types'
    end
  end

  get 'help' => 'help#index'
  get 'help/api' => 'help#api'
  get 'help/api/:category' => 'help#api', as: 'help_api_file'
end

app/models/atmosphere/fund.rb
# == Schema Information
#
# Table name: funds
#
#  id                 :integer          not null, primary key
#  name               :string(255)      default("unnamed fund"), not null
#  balance            :integer          default(0), not null
#  currency_label     :string(255)      default("EUR"), not null
#  overdraft_limit    :integer          default(0), not null
#  termination_policy :string(255)      default("suspend"), not null
#

# Fund
# Added by PN on 2014-01-14
# This class stores information on monetary resources which are used to pay
# for continued operation of virtual machines.
# Each user may belong to one or more fund and each fund may include multiple
# users Funds are linked to Appliances instead of VMs due to the fact that a s
# ingle VM may be shared by multiple Appliances (and therefore multiple users),
# in which case all owners "chip in" to enable continued operation of the VM.
# Funds are also linked to Tenants and may only be used to pay for VMs which
# belong to their respective Tenants.
module Atmosphere
  class Fund < ActiveRecord::Base
    extend Enumerize

    has_many :appliances,
             class_name: 'Atmosphere::Appliance'

    has_many :users,
             through: :user_funds,
             class_name: 'Atmosphere::User'

    has_many :user_funds,
             -> { includes(:user).order('atmosphere_users.full_name') },
             dependent: :destroy,
             class_name: 'Atmosphere::UserFund'

    has_many :tenants,
             through: :tenant_funds,
             class_name: 'Atmosphere::Tenant'

    has_many :tenant_funds,
             dependent: :destroy,
             class_name: 'Atmosphere::TenantFund'

    validates :name,
              presence: true

    validates :balance,
              numericality: {
                only_integer: true,
                less_than_or_equal_to: 2147483647
              }

    validates :overdraft_limit,
              numericality: { less_than_or_equal_to: 0 }

    validates :termination_policy,
              inclusion: { in: ['delete', 'suspend', 'no_action'] }

    enumerize :termination_policy,
              in: [:delete, :suspend, :no_action],
              predicates: true

    attr_readonly :name

    def unsupported_tenants
      Tenant.where.not(id: tenants)
    end

    def unassigned_users
      User.where.not(id: users).order(:full_name)
    end
  end
end

app/controllers/atmosphere/admin/funds_controller.rb
class Atmosphere::Admin::FundsController < Atmosphere::Admin::ApplicationController
  load_and_authorize_resource :fund, class: 'Atmosphere::Fund'

  # GET /funds
  def index
    @funds = @funds.order :name
  end

  # GET /funds/new
  def new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  def create
    if @fund.save
      redirect_to admin_funds_path, notice: t('funds.new.success')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /funds/1
  def update
    if @fund.update(update_params)
      redirect_to admin_funds_path, notice: t('funds.update.success')
    else
      render action: 'edit'
    end
  end

  # DELETE /funds/1
  def destroy
    @fund.destroy
    redirect_to admin_funds_url, notice: t('funds.destroy.success')
  end


  private

  def update_params
    params.require(:fund).
      permit(:balance, :overdraft_limit,
             :currency_label, :termination_policy)
  end

  def fund_params
    params.require(:fund).permit(
        :name,
        :balance, :overdraft_limit, :currency_label,
        :termination_policy
    )
  end

end

app/helpers/atmosphere/funds_helper.rb
module Atmosphere
  module FundsHelper

    def fund_balance_full_precision(balance)
      balance = balance.to_i
      "#{'-' if balance < 0}#{balance.abs / 10000}." +
      "#{(balance.abs % 10000).to_s.rjust(4, '0')}"
    end

    def last_months_names
      (Time.now.month - 12..Time.now.month).
          select { |m| m != 0 }.
          map { |m| Date::MONTHNAMES[m] }
    end

  end
end

app/views/atmosphere/admin/funds/_billing.html.haml
#billing

  %h3
    - mode_name = @user ? @user.full_name : 'all users'
    = t 'billing.consumption_title', user: mode_name
    .btn-group
      - if @user
        = link_to admin_billing_logs_path, remote: true,
          data: { billing: 'on' },
          class: 'btn btn-primary btn-sm has_bottom_tooltip' do
          = icon 'bar-chart'
          = t 'billing.load_for_all.label'
      %button#hide-billing.btn.btn-sm.btn-default
        = icon 'minus'
        = t 'hide'

  #billing-chart

  :javascript
    $(function () {
      $('#hide-billing').on('click', function() {
        $('#billing').empty();
      });

      new window.Billing(
        '#{mode_name}',
        #{last_months_names},
        #{@data_series}
      );
    });

app/views/atmosphere/admin/funds/_form.html.haml
= simple_form_for([:admin, @fund]) do |f|
  = f.error_notification

  .inputs
    = f.input :name, disabled: !@fund.new_record?
    .col-xs-4
      = f.input :balance, as: :integer
    .col-xs-4
      = f.input :overdraft_limit
    .col-xs-4
      = f.input :currency_label
    .span.help-block
      = t 'funds.new.balance_help'
    .col-xs-4
      = f.input :termination_policy
    .col-xs-8
      .span.help-block
        = t 'funds.new.termination_policy_help'
        %dl
          - Atmosphere::Fund.termination_policy.values.each do |termination_policy|
            %dd
              %strong= t "funds.termination_policies.#{termination_policy}.label"
            %dd= t "funds.termination_policies.#{termination_policy}.help"

  .actions
    = f.button :submit, class: 'btn btn-success'

app/views/atmosphere/admin/funds/_user_fund.html.haml
.btn-group
  - user = user_fund.user

  %span.btn.btn-default.btn-xs.disabled.non-opaque
    = user.full_name
    = surround '(', ')' do
      = user.login

  - if user_fund.default
    %span{ class: 'btn btn-xs btn-primary has_bottom_tooltip',
    title: t('funds.set_default.to_false',
             user: user_fund.user.full_name) }
      D
  - else
    .btn-group
      = form_for [:admin, user_fund] do |f|
        = f.hidden_field :default, value: true
        %button.btn.btn-xs.btn-default.has_bottom_tooltip{ type: 'submit',
        title: t('funds.set_default.to_true',
                 fund: user_fund.fund.name,
                 user: user_fund.user.full_name) }
          D

  = link_to admin_billing_logs_path(user_id: user.id),
    remote: true,
    data: { billing: 'on' },
    title: t('billing.load_for_user', user: user.full_name),
    class: 'btn btn-default btn-xs has_bottom_tooltip' do
    = icon 'bar-chart'

  = link_to admin_user_fund_path(user_fund),
    method: :delete,
    data: { confirm: t('are_you_sure') },
    class: 'btn btn-default btn-xs has_bottom_tooltip',
    title: t('funds.remove_user.help', user: user_fund.user) do
    = icon 'times'

app/views/atmosphere/admin/funds/edit.html.haml
%h1
  = t 'editing'
  = t 'funds.long_title_single'

= render 'form'

%p
  .btn-group
    = link_to admin_funds_path,
      class: 'btn btn-default', title: t('back') do
      =icon 'reply'
      = t 'back'

app/views/atmosphere/admin/funds/index.html.haml
%h1
  = t 'funds.long_title'
  .pull-right
    = link_to new_admin_fund_path,
      class: 'btn btn-success has_bottom_tooltip',
      title: t('funds.new.help') do
      = icon 'plus'
      = t 'add_new'

%p
  %table.table.table-hover.table-condensed
    %tr
      %th.col-md-2= t 'funds.name'
      %th
        .pull-right= t 'funds.balance'
      %th
      %th
        .pull-right= t 'funds.overdraft_limit'
      %th
      %th.text-center= t 'funds.termination_policy'
      %th.col-md-2
        .pull-right= t 'actions'

    - @funds.each do |fund|
      %tr
        %td(rowspan=3)= fund.name
        %td
          .pull-right= fund_balance_full_precision fund.balance
        %td= fund.currency_label
        %td
          .pull-right= fund_balance_full_precision fund.overdraft_limit
        %td= fund.currency_label
        %td.text-center
          - label_map = { suspend: :primary, no_action: :success, delete: :danger }
          %span{ class: "label label-#{label_map[fund.termination_policy.to_sym]} has_bottom_tooltip",
                 title: t("funds.termination_policies.#{fund.termination_policy}.help") }
            = t "funds.termination_policies.#{fund.termination_policy}.label"
        %td
          .btn-group.pull-right
            = link_to edit_admin_fund_path(fund),
              class: 'btn btn-warning btn-xs has_bottom_tooltip',
              title: t('funds.update.help') do
              = icon 'edit'
            = link_to admin_fund_path(fund),
              method: :delete,
              data: { confirm: t('are_you_sure') },
              class: 'btn btn-danger btn-xs has_bottom_tooltip',
              title: t('funds.destroy.help') do
              = icon 'trash-o'


      %tr
        %td(colspan=5)
          = succeed ':' do
            %strong= t 'tenants.title'
          - if fund.tenant_funds.present?
            - fund.tenant_funds.each do |tenant_fund|
              .btn-group
                %span.btn.btn-default.btn-xs.disabled.non-opaque
                  = tenant_fund.tenant.name
                = link_to admin_tenant_fund_path(tenant_fund),
                  method: :delete,
                  data: { confirm: t('are_you_sure') },
                  class: 'btn btn-default btn-xs has_bottom_tooltip',
                  title: t('funds.remove_tenant.help',
                           tenant: tenant_fund.tenant.name) do
                  = icon 'times'
          - else
            %i.text-muted
              = surround '(',')' do
                = t 'funds.no_tenants'
        %td
          - if fund.unsupported_tenants.present?
            = simple_form_for([:admin, Atmosphere::TenantFund.new(fund: fund)]) do |f|
              = f.association :fund, as: :hidden
              = f.association :tenant,
                collection: fund.unsupported_tenants,
                prompt: t('funds.add_tenant.prompt'),
                input_html: { class: 'form-control tiny-select has_bottom_tooltip self-submit',
                  title: t('funds.add_tenant.help') },
                wrapper_html: { class: 'tiny-select-wrapper' },
                label: false
          - else
            %i.text-muted.pull-right
              = surround '(',')' do
                = t 'funds.add_tenant.all_assigned'


      %tr
        %td(colspan=5)
          = succeed ':' do
            %strong= t 'users.title'
          - if fund.users.present?
            = render partial: 'user_fund', collection: fund.user_funds
          - else
            %i.text-muted
              = surround '(',')' do
                = t 'funds.no_users'
        %td
          - if fund.unassigned_users.present?
            = simple_form_for([:admin, Atmosphere::UserFund.new(fund: fund)]) do |f|
              = f.association :fund, as: :hidden
              = f.association :user,
                collection: fund.unassigned_users,
                label_method: :descriptive_name,
                prompt: t('funds.add_user.prompt'),
                input_html: { class: 'form-control tiny-select has_bottom_tooltip self-submit',
                  title: t('funds.add_user.help') },
                wrapper_html: { class: 'tiny-select-wrapper' },
                label: false
          - else
            %i.text-muted.pull-right
              = surround '(',')' do
                = t 'funds.add_user.all_assigned'


%hr

%h5#billing-chart-spinner.text-muted
  %em= t 'billing.loading'
  .inline-spinner

#billing


:javascript
  $('body').on('change', '.self-submit', function() {
    this.form.submit();
  });

  $(function() {
    $.get('#{admin_billing_logs_path}', function(data) {
      $('#billing').html(data);
    });
  });

  $('body').
    on('ajax:beforeSend', '[data-billing=on]', function(evt, data, status, xhr){
      $('#billing-chart-spinner').show();
    }).
    on('ajax:success', '[data-billing=on]', function(evt, data, status, xhr){
      $('#billing').html(data);
    });

app/views/atmosphere/admin/funds/new.html.haml
%h1
  = t 'new'
  = t 'funds.long_title_single'

= render 'form'

%p
  .btn-group
    = link_to admin_funds_path, class: 'btn btn-default', title: t('back') do
      = icon 'reply'
      = t 'back'